<a href="https://colab.research.google.com/github/prog815/lernDLpython/blob/master/%D1%80%D0%B0%D1%81%D0%BF%D0%BE%D0%B7%D0%BD%D0%B0%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B4%D0%B5%D0%B6%D0%B4%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
import numpy as np


In [0]:
(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

In [0]:
x_train.shape

(60000, 28, 28)

In [0]:
y_train.shape

(60000,)

In [0]:
x_train = x_train.reshape(60000,28*28)
x_train.shape

(60000, 784)

In [0]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   1,   0,   0,  13,  73,   0,   0,   1,
         4,   0,   0,   0,   0,   1,   1,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   3,   0,  36, 136, 127,  62,
        54,   0,   0,   0,   1,   3,   4,   0,   0,   3,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0, 102, 204,
       176, 134, 144, 123,  23,   0,   0,   0,   0,  12,  10,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [0]:
x_train = x_train / 255
x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [0]:
y_train[0]

9

In [0]:
y_train = utils.to_categorical(y_train,10)
y_train.shape

(60000, 10)

In [0]:
model = Sequential()
model.add(Dense(800,input_shape=(784,),activation="relu"))
model.add(Dense(10,activation="softmax"))

In [0]:
from keras import losses
from keras import optimizers

In [0]:
model.compile(loss="categorical_crossentropy",optimizer="SGD",metrics=["accuracy"])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 800)               628000    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                8010      
Total params: 636,010
Trainable params: 636,010
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.fit(x_train,y_train,batch_size=200,epochs=100)

Epoch 1/100
60000/60000 [==============================] - 1s 18us/sample - loss: 1.1409 - acc: 0.6609
Epoch 2/100
60000/60000 [==============================] - 1s 17us/sample - loss: 0.7252 - acc: 0.7755
Epoch 3/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.6339 - acc: 0.8015
Epoch 4/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.5849 - acc: 0.8142
Epoch 5/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.5533 - acc: 0.8208
Epoch 6/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.5305 - acc: 0.8267
Epoch 7/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.5133 - acc: 0.8303
Epoch 8/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.4996 - acc: 0.8335
Epoch 9/100
60000/60000 [==============================] - 1s 16us/sample - loss: 0.4880 - acc: 0.8367
Epoch 10/100
60000/60000 [==============================] - 1s 16us/sampl

In [0]:
x_test.shape

(10000, 28, 28)

In [0]:
prediction=model.predict(x_test.reshape(10000,28*28)/255)
prediction.shape

(10000, 10)

In [0]:
prediction[5]

array([4.4425754e-03, 9.9380189e-01, 4.2652281e-04, 5.3096632e-04,
       7.1410433e-04, 4.4599666e-10, 6.0700888e-05, 3.7939103e-08,
       2.3299262e-05, 3.4943504e-10], dtype=float32)

In [0]:
y_test[5]

1

In [0]:
n=1000
np.argmax(prediction[n]),y_test[n]

(6, 0)

In [0]:
res = 0
for n in range(len(y_test)):
  if np.argmax(prediction[n])==y_test[n]:
    res += 1
res

8712